# Site settings
title: d0x75 
description: 'reverse engineering , exploits, windows tricks'
url: 'https://github.com/d0x75'
baseurl: '/d0x75'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Eduardo B'
  email: dudsdev@gmail.com
  twitter_username: dudsdev
  facebook_username: dudsdev
  github_username:  d0x75
  linkedin_username:  eduardo-barbosa-da-silva-266a70135

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
